Register warden Mwita
code-423n4/code423n4.com pull request #11042
Opened 2023-06-24 17:10 UTC by code423n4

Auto-generated PR to register the new warden Mwita

@MwitahJob

2023-06-24 17:14 UTC, MwitahJob reviewed
Okay

2023-06-24 17:21 UTC, MwitahJob approved these changes

2023-06-24 17:36 UTC, MwitahJob requested changes
Merge.

2023-06-24 17:43 UTC, MwitahJob approved these changes
Make changes.

2023-06-24 17:43 UTC, MwitahJob commented on _data/handles/Mwita.json
> +}
Make changes.

2023-06-26 12:05 UTC, SamusElderg commented
Have contacted user to change their nickname to match application

2023-06-26 13:21 UTC, SamusElderg approved these changes

2023-06-26 13:23 UTC, merged