Edit team CodeFoxInc
code-423n4/code423n4.com pull request #11625
Opened 2023-07-22 00:00 UTC by code423n4

This auto-generated PR modifies the team CodeFoxInc

The request was made by TerrierLover

2023-07-24 08:21 UTC, Simon-Busch requested changes

2023-07-24 08:21 UTC, Simon-Busch commented on _data/handles/CodeFoxInc.json
> +  "image": "CmgZYdpuTKN",
```suggestion
  "image": "./avatars/CodeFoxInc.png",
```

2023-07-24 14:59 UTC, itsmetechjay approved these changes

2023-07-26 23:39 UTC, itsmetechjay commented
@Simon-Busch I think I committed your changes but it still says "merging is blocked" - do you need to approve it maybe?

2023-07-27 11:35 UTC, Simon-Busch approved these changes

2023-07-27 11:35 UTC, merged