Edit team Audit_Avengers_2
code-423n4/code423n4.com pull request #11655
Opened 2023-07-23 13:06 UTC by code423n4

This auto-generated PR modifies the team Audit_Avengers_2

The request was made by JP_Courses

2023-07-23 14:45 UTC, itsmetechjay approved these changes

2023-07-24 08:20 UTC, Simon-Busch requested changes

2023-07-24 08:20 UTC, Simon-Busch commented on _data/handles/Audit_Avengers_2.json
> +  "image": "KsXtxH34xkg",
```suggestion
  "image": "./avatars/Audit_Avengers_2.png",
```

2023-07-24 13:35 UTC, itsmetechjay approved these changes

2023-08-01 01:47 UTC, itsmetechjay commented
@Simon-Busch may need you to merge this one? I think I committed your changes.

2023-08-01 05:23 UTC, Simon-Busch approved these changes

2023-08-01 05:24 UTC, merged