Warden Auth
code-423n4/code423n4.com pull request #1186
Opened 2022-03-04 00:41 UTC by joshuashort

2022-05-26 08:04 UTC, Simon-Busch requested changes

2022-05-26 08:04 UTC, Simon-Busch commented on package.json
> +    "isomorphic-dompurify": "^0.19.0",
! duplicate of "isomorphic-dompurify"
```suggestion
```

2022-05-26 08:04 UTC, Simon-Busch commented on src/components/Login/Login.tsx
> +          Connect WalletConnect
Missing image in /static/images

2022-05-26 08:04 UTC, Simon-Busch commented on src/components/Login/Login.tsx
> +        </a>
Missing image in /static/images

2022-05-26 08:04 UTC, Simon-Busch commented on src/components/Login/Login.tsx
> +          />
Missing image in /static/images

2022-05-26 14:10 UTC, Simon-Busch commented on package.json
> +    "isomorphic-dompurify": "^0.19.0",
Done in my commit [faefe57](https://github.com/code-423n4/code423n4.com/pull/1186/commits/faefe57a9be65bc7a97aec57062757e5a9f410ab)

2022-06-01 10:43 UTC, Simon-Busch commented on src/components/Login/Login.tsx
> +        </a>
added in https://github.com/code-423n4/code423n4.com/pull/2047

2022-06-01 10:43 UTC, Simon-Busch commented on src/components/Login/Login.tsx
> +          />
added in https://github.com/code-423n4/code423n4.com/pull/2047

2022-06-02 19:02 UTC, captainmangoC4 commented on functions/register-warden.js
> +    if ((!isUpdate && response.ok) || userData.moralisId) {
```suggestion
    if (!isUpdate && (response.ok || userData.moralisId)) {
```

2022-06-02 19:08 UTC, captainmangoC4 commented on functions/register-warden.js
> +    }
```suggestion
        const content = JSON.stringify(
          {
            ...userData,
            moralisId,
          },
          null,
          2
        );
        files[`_data/handles/${handle}.json`] = content;
    }
```

2022-06-02 19:10 UTC, captainmangoC4 commented on functions/register-warden.js
> +    }
user data is already fetched on line 132

2022-06-09 07:09 UTC, joshuashort commented on .gitignore
> +.netlify
dup.

```suggestion
```

2022-06-24 15:46 UTC, Simon-Busch approved these changes

2022-06-25 00:14 UTC, captainmangoC4 commented on _data/handles/CaptainMango.json
> +}
I think it's fine to leave them in. We will be able to use them in the future for other testing purposes. A few other team members have warden accounts as well.

2022-06-28 06:28 UTC, sockdrawermoney commented
🎉

2022-06-28 06:33 UTC, Simon-Busch commented
As discussed with @captainmangoC4 we will re-work the ability and impact of updating the C4 username after the launch.

reference to [7d53f2f](https://github.com/code-423n4/code423n4.com/pull/1186/commits/7d53f2fbc2a6a65082327efe5edfe066f78d5996)

2022-06-28 15:56 UTC, merged