Register warden atoko
code-423n4/code423n4.com pull request #12494
Opened 2023-09-02 17:13 UTC by code423n4

Auto-generated PR to register the new warden atoko

@pratokko

2023-09-02 18:20 UTC, pratokko reviewed
review

2023-09-02 18:26 UTC, pratokko requested changes
viewed review

2023-09-02 18:27 UTC, pratokko reviewed
changed to comment

2023-09-02 18:28 UTC, pratokko approved these changes
approve

2023-09-04 04:05 UTC, sksb2180 approved these changes

2023-09-04 04:12 UTC, merged