Create team Code4renaGroup
code-423n4/code423n4.com pull request #17094
Opened 2024-12-14 19:57 UTC by code423n4

This auto-generated PR creates the team Code4renaGroup

2024-12-17 10:57 UTC, 0xtr3 approved these changes

2024-12-17 10:57 UTC, 0xtr3 reviewed
It looks fine. All correct.

2024-12-17 10:58 UTC, 0xtr3 approved these changes
We better use the Code4rena team submission. I will chase up with Code4rena.

2024-12-20 16:31 UTC, thebrittfactor requested changes
Requested via discord [message](https://discord.com/channels/810916927919620096/1318217721967542383/1318221346710360094) to debo to have the team name changed and re-submit, as we are concerned that it could be perceived as a C4 staff team.

2025-01-02 16:55 UTC, closed without merging