Re-work reset registration form
code-423n4/code423n4.com pull request #2099
Opened 2022-06-03 09:45 UTC by Simon-Busch

- [ ] update register component -> change to modal
- [ ] update modal component and context
- [ ] pass resetForm to registration form component

2022-06-03 09:49 UTC, Simon-Busch commented
@captainmangoC4 I took the liberty to adapt the component to use our great modal, I think it makes sense in the case, let me know what you think about it :-)

2022-06-06 17:10 UTC, captainmangoC4 requested changes

2022-06-06 17:10 UTC, captainmangoC4 commented on src/pages/register.tsx
> +  };
Apologies - it seems we had a miscommunication about this. We should actually show the error message on the page, like we do with error messages on other forms, not in a modal.

The issue with the form state resetting when an error occurs is due to the fact that the error state is managed outside of the form component. The `register` page component manages the error state, so when an error occurs, the `RegisterForm` component is unmounted and the error message is shown instead. Then, when the error state is reset and we show the form again, it is actually remounting the form component with blank state. If we either 1. manage error state inside `RegisterForm`, or 2. remove `RegisterForm` altogether and move its contents directly into `register` page component, we can solve this problem.

2022-06-07 18:20 UTC, captainmangoC4 approved these changes

2022-06-07 18:20 UTC, merged