1041 ensure handle link is absolute url
code-423n4/code423n4.com pull request #2184
Opened 2022-06-14 09:03 UTC by hannahtuttle

This adds validation to the link input in the warden-registration, it also changed the placeholder in the input field and updates a few warden links to be absolute links. Needs to wait for warden auth before changes can be made.

2022-06-30 13:23 UTC, Simon-Busch requested changes

2022-06-30 13:23 UTC, Simon-Busch commented on src/components/RegistrationForm.tsx
> +
```suggestion
```

I would simply handle is the same way we handle the discord username validation, see here:

```javascript
  const handleChange = useCallback((e) => {
    const { name, value } = e.target;
    setState((prevState) => {
      return { ...prevState, [name]: value };
    });
    if (name === "discordUsername") {
      setIsValidDiscord(discordUsernameRegex.test(value));
    }
    if (name === "username") {
      setisDangerousUsername(value.match(/^[0-9a-zA-Z_\-]+$/) === null);
    }
  }, []);
```

2022-07-06 08:31 UTC, Simon-Busch approved these changes

2022-07-09 00:50 UTC, joshuashort commented on src/components/RegistrationForm.tsx
> +  const checkAbsoluteURL = new RegExp("^(?:[a-z]+:)?//", "i");
Specifically http(s)?

```suggestion
  const checkAbsoluteURL = new RegExp("^(http[s]?)://", "i");
```

2022-07-09 00:53 UTC, joshuashort commented on src/components/RegistrationForm.tsx
> +                    Please provide a valid url. "https://domain_name" required.
```suggestion
                    Please provide a valid http(s) url.
```

2022-10-25 07:21 UTC, Simon-Busch commented
As discussed with @hannahtuttle We can close this P.R.

2022-10-25 07:21 UTC, closed without merging