register apoorvlathey as warden
code-423n4/code423n4.com pull request #253
Opened 2021-09-12 14:32 UTC by CodinMaster

2021-09-12 17:24 UTC, ninek9 requested changes
need to drop the avatar in “avatars” sub folder

2021-09-13 01:17 UTC, CodinMaster commented
> need to drop the avatar in “avatars” sub folder

Hey, it's already there. Isn't this the right folder?
https://github.com/code-423n4/code423n4.com/blob/2c4dd694fbb74dd80beaf63db0fa7d19a249dca6/_data/handles/avatars/apoorvlathey.png

2021-09-13 01:19 UTC, ninek9 approved these changes

2021-09-13 01:19 UTC, ninek9 commented
my fault, read too fast! sorry about that:)

2021-09-13 01:21 UTC, merged