Register warden belzburl
code-423n4/code423n4.com pull request #3479
Opened 2022-08-15 11:33 UTC by code423n4

Auto-generated PR to register the new warden belzburl

2022-08-16 11:48 UTC, kaiili approved these changes

2022-08-16 11:49 UTC, kaiili approved these changes

2022-08-16 11:50 UTC, kaiili requested changes
ok

2022-08-22 21:35 UTC, itsmetechjay commented
Registration incomplete - did not introduce self in Discord.

2022-08-22 21:35 UTC, closed without merging